# This workflow validates, deploys, and runs the specified bundle
# within a pre-production target named "dev".
name: "STG Bundle Teardown"

# Ensure that only a single job or workflow using the same concurrency group
# runs at a time.
concurrency: 1

# Trigger this workflow whenever a pull request is opened against the repo's
# dev branch or run it manually.
on:
  workflow_dispatch:
    inputs:
      bundle:
        type: choice
        description: Bundle to destroy
        options:
        - common
        - core_games
        - coretech
        - horizon
        - mobile
        - standard_metrics
        - cdp
        - sports
        - utils

env:
  DBX_SP_TOKEN: ${{ secrets.DBX_SP_TOKEN }}
  DATABRICKS_CLIENT_ID: ${{ secrets.DBX_STG_CLIENT_ID }}
  DATABRICKS_CLIENT_SECRET: ${{ secrets.DBX_STG_CLIENT_SECRET }}

jobs:
  # Used by the "pipeline_update" job to deploy the bundle.
  # Bundle validation is automatically performed as part of this deployment.
  # If validation fails, this workflow fails.
  deploy:
    name: "Destroy stg bundle"
    runs-on: ubuntu-latest
    env:
      DBX_SP_TOKEN: ${{ secrets.DBX_SP_TOKEN }}
      DATABRICKS_CLIENT_ID: ${{ secrets.DBX_STG_CLIENT_ID }}
      DATABRICKS_CLIENT_SECRET: ${{ secrets.DBX_STG_CLIENT_SECRET }}

    steps:
      # Check out this repo, so that this workflow can access it.
      - uses: actions/checkout@v3

      # Download the Databricks CLI.
      # See https://github.com/databricks/setup-cli
      - uses: databricks/setup-cli@main

      # Deploy the bundle to the "qa" target as defined
      # in the bundle's settings file.
      - run: cd DNA/${{ github.event.inputs.bundle }} && databricks bundle destroy --target stg --auto-approve
        working-directory: .
        env:
          DATABRICKS_TOKEN: ${{ secrets.DBX_SP_TOKEN }}
          DATABRICKS_BUNDLE_ENV: stg

          
