resources:
  jobs:
    wwesc_master_id_weekly:
      name: wwesc_master_id_weekly
      max_concurrent_runs: 1

      webhook_notifications:
        on_failure:
          - id: ${var.slack_webhook}

      schedule:
        quartz_cron_expression: "0 0 1 ? * MON"  # Every Monday at 01:00 UTC
        timezone_id: UTC
        pause_status: ${var.schedule_status}

      tasks:
        - task_key: wwesc_master_id_task
          job_cluster_key: master_id_cluster${var.environment}
          notebook_task:
            notebook_path: ../master_id/src/batch/managed/wwesc_mobile_master_id.py
            base_parameters:
              inputParam: '{"environment":"${var.environment}"}'
              checkpoint: 'dbfs:/tmp/mobile/managed/batch/run${var.environment}/wwesc_master_id_map'
          libraries:
            - maven:
                coordinates: "graphframes:graphframes:0.8.3-spark3.5-s_2.12"

        - task_key: snowflake_refresh_managed
          job_cluster_key: master_id_cluster${var.environment}
          notebook_task:
            notebook_path: ../../utils/src/snowflake/refresh_snowflake_iceberg_tables.py
            base_parameters:
              inputParam: '{"environment":"${var.environment}"}'
              environment: ${var.environment}
              title: mobile
              dbx_catalog: mobile${var.environment}
              dbx_schema: managed
          depends_on:
            - task_key: wwesc_master_id_task

      job_clusters:
        - job_cluster_key: master_id_cluster${var.environment}
          new_cluster:
            data_security_mode: SINGLE_USER
            spark_version: 16.4.x-scala2.12
            aws_attributes:
              availability: ON_DEMAND
            node_type_id: ${var.node_type_id}
            driver_node_type_id: ${var.driver_node_type_id}
            autoscale:
              min_workers: ${var.num_workers}
              max_workers: ${var.max_num_workers}
            init_scripts:
              - workspace:
                  destination: /Shared/datadog/dd_init.sh
            spark_conf:
              "spark.driver.extraJavaOptions": "-XX:+UseZGC"
            spark_env_vars:
              DD_API_KEY: "{{secrets/data-engineering/dd_api_key}}"
            custom_tags:
              owner: "Data Engineering"

      tags:
        business_unit: "Mobile"
        catalog: "mobile${var.environment}"
        data_layer: "managed"
        environment: ${var.environment}

      permissions:
        - level: CAN_MANAGE
          group_name: "dna live"
        - level: CAN_MANAGE
          group_name: "data engineering"